Repository 8-jokim-bizarre-adventure/backend, pull requests merged in 2024-09, with the labels that each got.

#18 Feature/products
  build.gradle
  src/main/java/com/jokim/sivillage/SivillageApplication.java
  src/main/java/com/jokim/sivillage/api/brand/Brand.java
  src/main/java/com/jokim/sivillage/api/brand/FavoriteBrandList.java
  src/main/java/com/jokim/sivillage/api/domain/Hashtag.java
  src/main/java/com/jokim/sivillage/api/event/application/EventService.java
  src/main/java/com/jokim/sivillage/api/event/application/EventServiceImpl.java
  src/main/java/com/jokim/sivillage/api/event/domain/Event.java
  src/main/java/com/jokim/sivillage/api/event/domain/EventImageList.java
  src/main/java/com/jokim/sivillage/api/event/domain/EventProductList.java
  src/main/java/com/jokim/sivillage/api/event/domain/EventWishList.java
  src/main/java/com/jokim/sivillage/api/event/dto/EventResponseDto.java
  src/main/java/com/jokim/sivillage/api/event/infrastructure/EventRepository.java
  src/main/java/com/jokim/sivillage/api/event/presentation/EventController.java
  src/main/java/com/jokim/sivillage/api/image/Image.java
  src/main/java/com/jokim/sivillage/api/product/application/ProductService.java
  src/main/java/com/jokim/sivillage/api/product/application/ProductServiceImpl.java
  src/main/java/com/jokim/sivillage/api/product/domain/HotDeal.java
  src/main/java/com/jokim/sivillage/api/product/domain/Product.java
  src/main/java/com/jokim/sivillage/api/product/domain/ProductCategoryList.java
  src/main/java/com/jokim/sivillage/api/product/domain/ProductHashtag.java
  src/main/java/com/jokim/sivillage/api/product/domain/ProductHit.java
  src/main/java/com/jokim/sivillage/api/product/domain/ProductImageList.java
  src/main/java/com/jokim/sivillage/api/product/domain/ProductOption.java
  src/main/java/com/jokim/sivillage/api/product/domain/ProductSalesVolume.java
  src/main/java/com/jokim/sivillage/api/product/domain/ProductStatistics.java
  src/main/java/com/jokim/sivillage/api/product/domain/ProductWishList.java
  src/main/java/com/jokim/sivillage/api/product/domain/option/Color.java
  src/main/java/com/jokim/sivillage/api/product/domain/option/Etc.java
  src/main/java/com/jokim/sivillage/api/product/domain/option/Size.java
  src/main/java/com/jokim/sivillage/api/product/dto/in/ProductRequestDto.java
  src/main/java/com/jokim/sivillage/api/product/dto/out/DailyHotProductResponseDto.java
  src/main/java/com/jokim/sivillage/api/product/dto/out/FilteredProductDto.java
  src/main/java/com/jokim/sivillage/api/product/dto/out/ProductResponseDto.java
  src/main/java/com/jokim/sivillage/api/product/infrastructure/ProductRepository.java
  src/main/java/com/jokim/sivillage/api/product/presentation/ProductController.java
  src/main/java/com/jokim/sivillage/api/product/vo/in/ProductRequestVo.java
  src/main/java/com/jokim/sivillage/api/product/vo/out/DailyHotProductResponseVo.java
  src/main/java/com/jokim/sivillage/api/product/vo/out/ProductResponseVo.java
  src/main/resources/data.sql
  src/test/java/com/jokim/sivillage/SivillageApplicationTests.java
Labels: ✨ enhancement, ⚡️ improve

#21 Refactoring 및 배포 workflow 수정
  .github/workflows/cicd.yml
  build.gradle
  src/main/java/com/jokim/sivillage/api/brand/Brand.java
  src/main/java/com/jokim/sivillage/api/brand/FavoriteBrandList.java
  src/main/java/com/jokim/sivillage/api/customer/domain/State.java
  src/main/java/com/jokim/sivillage/api/event/domain/Event.java
  src/main/java/com/jokim/sivillage/api/event/domain/EventImageList.java
  src/main/java/com/jokim/sivillage/api/event/domain/EventWishList.java
  src/main/java/com/jokim/sivillage/api/event/dto/EventResponseDto.java
  src/main/java/com/jokim/sivillage/api/hashtag/domain/Hashtag.java
  src/main/java/com/jokim/sivillage/api/media/domain/Media.java
  src/main/java/com/jokim/sivillage/api/product/domain/HotDeal.java
  src/main/java/com/jokim/sivillage/api/product/domain/Product.java
  src/main/java/com/jokim/sivillage/api/product/domain/ProductCategoryList.java
  src/main/java/com/jokim/sivillage/api/product/domain/ProductHashtag.java
  src/main/java/com/jokim/sivillage/api/product/domain/ProductHit.java
  src/main/java/com/jokim/sivillage/api/product/domain/ProductImageList.java
  src/main/java/com/jokim/sivillage/api/product/domain/ProductSalesVolume.java
  src/main/java/com/jokim/sivillage/api/product/domain/ProductStatistics.java
  src/main/java/com/jokim/sivillage/api/product/vo/out/ProductResponseVo.java
  src/main/java/com/jokim/sivillage/common/entity/BaseEntity.java
  src/test/java/com/jokim/sivillage/SivillageApplicationTests.java
Labels: ♻️ refactor, 👷 chore

#23 Category CRUD API 구현 및 build 관련 수정
  .github/pull_request_template.md
  .github/workflows/cicd.yml
  .gitignore
  src/main/java/com/jokim/sivillage/api/category/application/CategoryService.java
  src/main/java/com/jokim/sivillage/api/category/application/CategoryServiceImpl.java
  src/main/java/com/jokim/sivillage/api/category/domain/Category.java
  src/main/java/com/jokim/sivillage/api/category/dto/CategoryRequestDto.java
  src/main/java/com/jokim/sivillage/api/category/dto/CategoryResponseDto.java
  src/main/java/com/jokim/sivillage/api/category/infrastructure/CategoryRepository.java
  src/main/java/com/jokim/sivillage/api/category/presentation/CategoryController.java
  src/main/java/com/jokim/sivillage/api/category/vo/in/CreateCategoryRequestVo.java
  src/main/java/com/jokim/sivillage/api/category/vo/in/UpdateCategoryRequestVo.java
  src/main/java/com/jokim/sivillage/api/category/vo/out/GetCategoryResponseVo.java
  src/main/java/com/jokim/sivillage/common/entity/BaseResponse.java
  src/main/java/com/jokim/sivillage/common/entity/BaseResponseStatus.java
  src/main/java/com/jokim/sivillage/common/exception/BaseException.java
  src/main/java/com/jokim/sivillage/common/exception/BaseExceptionHandler.java
  src/main/java/com/jokim/sivillage/common/utils/CodeGenerator.java
Labels: 📝 docs, ✨ enhancement, ✅ test, ♻️ refactor, 👷 chore, ⚡️ improve

#33 Hotfix: Swagger Server 요청 URL 달라서 생긴 에러 해결
  src/main/java/com/jokim/sivillage/api/category/presentation/CategoryController.java
  src/main/java/com/jokim/sivillage/api/product/presentation/ProductController.java
  src/main/java/com/jokim/sivillage/common/config/SwaggerConfig.java
  src/main/resources/data.sql
Labels: ✨ enhancement, 🚑️ hotfix

#37 ProductCategoryList API 구현
  build.gradle
  src/main/java/com/jokim/sivillage/api/bridge/application/ProductCategoryListService.java
  src/main/java/com/jokim/sivillage/api/bridge/application/ProductCategoryListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/domain/ProductCategoryList.java
  src/main/java/com/jokim/sivillage/api/bridge/dto/ProductCategoryListRequestDto.java
  src/main/java/com/jokim/sivillage/api/bridge/dto/ProductCategoryListResponseDto.java
  src/main/java/com/jokim/sivillage/api/bridge/infrastructure/ProductCategoryListRepository.java
  src/main/java/com/jokim/sivillage/api/bridge/infrastructure/ProductCategoryListRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/bridge/infrastructure/ProductCategoryListRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/presentation/ProductCategoryListController.java
  src/main/java/com/jokim/sivillage/api/bridge/vo/AddProductCategoryListRequestVo.java
  src/main/java/com/jokim/sivillage/api/bridge/vo/GetProductCategoryListResponseVo.java
  src/main/java/com/jokim/sivillage/api/category/application/CategoryServiceImpl.java
  src/main/java/com/jokim/sivillage/api/category/presentation/CategoryController.java
  src/main/java/com/jokim/sivillage/common/config/QuerydslConfig.java
  src/main/java/com/jokim/sivillage/common/config/SecurityConfig.java
  src/main/java/com/jokim/sivillage/common/entity/CommonResponseEntity.java
  src/main/java/com/jokim/sivillage/common/entity/CommonResponseMessage.java
  src/main/java/com/jokim/sivillage/common/utils/CodeGenerator.java
  src/main/java/com/jokim/sivillage/common/utils/CursorPage.java
Labels: ✨ enhancement, ✅ test, ♻️ refactor, 👷 chore

#38 Media API 구현
  src/main/java/com/jokim/sivillage/api/media/application/MediaService.java
  src/main/java/com/jokim/sivillage/api/media/application/MeidaServiceImpl.java
  src/main/java/com/jokim/sivillage/api/media/domain/Media.java
  src/main/java/com/jokim/sivillage/api/media/domain/MediaType.java
  src/main/java/com/jokim/sivillage/api/media/dto/MediaRequestDto.java
  src/main/java/com/jokim/sivillage/api/media/dto/MediaResponseDto.java
  src/main/java/com/jokim/sivillage/api/media/infrastructure/MediaRepository.java
  src/main/java/com/jokim/sivillage/api/media/presentation/MediaController.java
  src/main/java/com/jokim/sivillage/api/media/vo/in/AddMediaRequestVo.java
  src/main/java/com/jokim/sivillage/api/media/vo/in/UpdateMediaRequestVo.java
  src/main/java/com/jokim/sivillage/api/media/vo/out/GetMediaResponseVo.java
  src/main/java/com/jokim/sivillage/common/entity/BaseResponseStatus.java
  src/main/java/com/jokim/sivillage/common/utils/CodeGenerator.java
Labels: ✨ enhancement, ✅ test

#39 ProductMediaList, ReviewMediaList API 구현
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/application/ProductMediaListService.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/application/ProductMediaListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/domain/ProductMediaList.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/dto/in/ProductMediaListRequestDto.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/dto/out/ProductMediaListResponseDto.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/infrastructure/ProductMediaListRepository.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/presentation/ProductMediaListController.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/vo/in/AddProductMediaListRequestVo.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/vo/in/UpdateProductMediaListRequestVo.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/vo/out/GetProductMediaListResponseVo.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/application/ReviewMediaListService.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/application/ReviewMediaListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/domain/ReviewMediaList.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/dto/ReviewMediaListRequestDto.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/dto/ReviewMediaListResponseDto.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/infrastructure/ReviewMediaListRepository.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/presentation/ReviewMediaListController.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/vo/AddReviewMediaListRequestVo.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/vo/GetReviewMediaListResponseVo.java
  src/main/java/com/jokim/sivillage/common/entity/BaseResponseStatus.java
Labels: ✨ enhancement, ✅ test, ♻️ refactor

#44 Event-Media-List, Brand-Media-List API 구현 및 Category 관련 Refactoring
  src/main/java/com/jokim/sivillage/api/bridge/application/ProductCategoryListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/brandmedialist/application/BrandMediaListService.java
  src/main/java/com/jokim/sivillage/api/bridge/brandmedialist/application/BrandMediaListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/brandmedialist/domain/BrandMediaList.java
  src/main/java/com/jokim/sivillage/api/bridge/brandmedialist/dto/BrandMediaListRequestDto.java
  src/main/java/com/jokim/sivillage/api/bridge/brandmedialist/dto/BrandMediaListResponseDto.java
  src/main/java/com/jokim/sivillage/api/bridge/brandmedialist/infrastructure/BrandMediaListRepository.java
  src/main/java/com/jokim/sivillage/api/bridge/brandmedialist/presentation/BrandMediaListController.java
  src/main/java/com/jokim/sivillage/api/bridge/brandmedialist/vo/AddBrandMediaListRequestVo.java
  src/main/java/com/jokim/sivillage/api/bridge/brandmedialist/vo/GetBrandMediaListResponseVo.java
  src/main/java/com/jokim/sivillage/api/bridge/eventmedialist/application/EventMediaListService.java
  src/main/java/com/jokim/sivillage/api/bridge/eventmedialist/application/EventMediaListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/eventmedialist/domain/EventMediaList.java
  src/main/java/com/jokim/sivillage/api/bridge/eventmedialist/dto/EventMediaListRequestDto.java
  src/main/java/com/jokim/sivillage/api/bridge/eventmedialist/dto/EventMediaListResponseDto.java
  src/main/java/com/jokim/sivillage/api/bridge/eventmedialist/infrastructure/EventMediaListRepository.java
  src/main/java/com/jokim/sivillage/api/bridge/eventmedialist/presentation/EventMediaListController.java
  src/main/java/com/jokim/sivillage/api/bridge/eventmedialist/vo/in/AddEventMediaListRequestVo.java
  src/main/java/com/jokim/sivillage/api/bridge/eventmedialist/vo/in/UpdateEventMediaListRequestVo.java
  src/main/java/com/jokim/sivillage/api/bridge/eventmedialist/vo/out/GetEventMediaListResponseVo.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/application/ProductCategoryListService.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/application/ProductCategoryListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/domain/ProductCategoryList.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/dto/ProductCategoryListRequestDto.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/dto/ProductCategoryListResponseDto.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/infrastructure/ProductCategoryListRepository.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/infrastructure/ProductCategoryListRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/infrastructure/ProductCategoryListRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/presentation/ProductCategoryListController.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/vo/AddProductCategoryListRequestVo.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/vo/GetProductCategoryListResponseVo.java
  src/main/java/com/jokim/sivillage/api/category/application/CategoryService.java
  src/main/java/com/jokim/sivillage/api/category/application/CategoryServiceImpl.java
  src/main/java/com/jokim/sivillage/api/category/presentation/CategoryController.java
  src/main/java/com/jokim/sivillage/api/media/application/MeidaServiceImpl.java
  src/main/java/com/jokim/sivillage/api/media/domain/Media.java
  src/main/java/com/jokim/sivillage/api/media/domain/MediaType.java
  src/main/java/com/jokim/sivillage/common/entity/BaseResponseStatus.java
  src/main/java/com/jokim/sivillage/common/utils/CursorPage.java
Labels: ✨ enhancement, ✅ test, ♻️ refactor, 🛠️ data processing

#49 Brand API 구현
  src/main/java/com/jokim/sivillage/api/brand/application/BrandService.java
  src/main/java/com/jokim/sivillage/api/brand/application/BrandServiceImpl.java
  src/main/java/com/jokim/sivillage/api/brand/domain/Brand.java
  src/main/java/com/jokim/sivillage/api/brand/dto/BrandRequestDto.java
  src/main/java/com/jokim/sivillage/api/brand/dto/BrandResponseDto.java
  src/main/java/com/jokim/sivillage/api/brand/infrastructure/BrandRepository.java
  src/main/java/com/jokim/sivillage/api/brand/presentation/BrandController.java
  src/main/java/com/jokim/sivillage/api/brand/vo/in/AddBrandRequestVo.java
  src/main/java/com/jokim/sivillage/api/brand/vo/in/UpdateBrandRequestVo.java
  src/main/java/com/jokim/sivillage/api/brand/vo/out/BrandDetailResponseVo.java
  src/main/java/com/jokim/sivillage/api/brand/vo/out/BrandSummaryResponseVo.java
  src/main/java/com/jokim/sivillage/api/bridge/brandmedialist/application/BrandMediaListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/brandmedialist/domain/BrandMediaList.java
  src/main/java/com/jokim/sivillage/api/bridge/brandmedialist/dto/BrandMediaListRequestDto.java
  src/main/java/com/jokim/sivillage/api/bridge/brandmedialist/dto/BrandMediaListResponseDto.java
  src/main/java/com/jokim/sivillage/api/bridge/brandmedialist/infrastructure/BrandMediaListRepository.java
  src/main/java/com/jokim/sivillage/api/bridge/brandmedialist/vo/AddBrandMediaListRequestVo.java
  src/main/java/com/jokim/sivillage/api/bridge/brandmedialist/vo/GetBrandMediaListResponseVo.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/domain/ProductCategoryList.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/dto/ProductCategoryListRequestDto.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/infrastructure/ProductCategoryListRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/vo/AddProductCategoryListRequestVo.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/application/ProductMediaListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/infrastructure/ProductMediaListRepository.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/application/ReviewMediaListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/infrastructure/ReviewMediaListRepository.java
  src/main/java/com/jokim/sivillage/common/entity/BaseResponseStatus.java
Labels: ✨ enhancement, ✅ test

#53 :recycle: refactor: try-catch refactoring
  src/main/java/com/jokim/sivillage/api/customer/application/CustomerServiceImpl.java
  src/main/java/com/jokim/sivillage/api/customer/presentation/CustomerController.java
  src/main/java/com/jokim/sivillage/common/entity/BaseResponseStatus.java
Labels: ♻️ refactor

#54 찜하기 및 좋아요 API 구현
  src/main/java/com/jokim/sivillage/api/brand/application/BrandService.java
  src/main/java/com/jokim/sivillage/api/brand/application/BrandServiceImpl.java
  src/main/java/com/jokim/sivillage/api/brand/domain/FavoriteBrandList.java
  src/main/java/com/jokim/sivillage/api/brand/dto/BrandRequestDto.java
  src/main/java/com/jokim/sivillage/api/brand/infrastructure/BrandRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/brand/presentation/BrandController.java
  src/main/java/com/jokim/sivillage/api/bridge/brandproductlist/domain/BrandProductList.java
  src/main/java/com/jokim/sivillage/api/bridge/brandproductlist/repository/BrandProductListRepository.java
  src/main/java/com/jokim/sivillage/api/event/domain/EventWishList.java
  src/main/java/com/jokim/sivillage/api/product/application/ProductServiceImpl.java
  src/main/java/com/jokim/sivillage/api/review/like/application/ReviewLikeListService.java
  src/main/java/com/jokim/sivillage/api/review/like/application/ReviewLikeListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/review/like/domain/ReviewLikeList.java
  src/main/java/com/jokim/sivillage/api/review/like/dto/ReviewLikeListRequestDto.java
  src/main/java/com/jokim/sivillage/api/review/like/dto/ReviewLikeListResponseDto.java
  src/main/java/com/jokim/sivillage/api/review/like/infrastructure/ReviewLikeListRepository.java
  src/main/java/com/jokim/sivillage/api/review/like/presentation/ReviewLikeListController.java
  src/main/java/com/jokim/sivillage/api/review/like/vo/AddReviewLikeListRequestVo.java
  src/main/java/com/jokim/sivillage/api/review/like/vo/GetReviewLikeListResponseVo.java
  src/main/java/com/jokim/sivillage/api/wishlist/brandwishlist/application/BrandWishlistService.java
  src/main/java/com/jokim/sivillage/api/wishlist/brandwishlist/application/BrandWishlistServiceImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/brandwishlist/domain/BrandWishlist.java
  src/main/java/com/jokim/sivillage/api/wishlist/brandwishlist/dto/BrandWishlistRequestDto.java
  src/main/java/com/jokim/sivillage/api/wishlist/brandwishlist/dto/BrandWishlistResponseDto.java
  src/main/java/com/jokim/sivillage/api/wishlist/brandwishlist/infrastructure/BrandWishlistRepository.java
  src/main/java/com/jokim/sivillage/api/wishlist/brandwishlist/presentation/BrandWishlistController.java
  src/main/java/com/jokim/sivillage/api/wishlist/brandwishlist/vo/in/AddBrandWishlistRequestVo.java
  src/main/java/com/jokim/sivillage/api/wishlist/brandwishlist/vo/out/GetAllBrandWishlistResponseVo.java
  src/main/java/com/jokim/sivillage/api/wishlist/brandwishlist/vo/out/GetBrandWishlistStateResponseVo.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/application/EventWishlistService.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/application/EventWishlistServiceImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/domain/EventWishlist.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/dto/EventWishlistRequestDto.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/dto/EventWishlistResponseDto.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/infrastructure/EventWishlistRepository.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/presentation/EventWishlistController.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/vo/in/AddEventWishlistRequestVo.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/vo/out/GetAllEventWishlistResponseVo.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/vo/out/GetEventWishlistStateResponseVo.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/application/ProductWishlistService.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/application/ProductWishlistServiceImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/domain/ProductWishlist.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/dto/ProductWishlistRequestDto.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/dto/ProductWishlistResponseDto.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/infrastructure/ProductWishlistRepository.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/presentation/ProductWishlistController.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/vo/in/AddProductWishlistRequestVo.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/vo/out/GetAllProductWishlistResponseVo.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/vo/out/GetProductWishlistStateResponseVo.java
  src/main/java/com/jokim/sivillage/common/entity/BaseEntity.java
  src/main/java/com/jokim/sivillage/common/jwt/JwtTokenProvider.java
  src/main/java/com/jokim/sivillage/common/utils/TokenExtractor.java
Labels: ✨ enhancement, ✅ test, ♻️ refactor, ⚡️ improve

#63 :bug: fix: resolve hotfix
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/application/ProductCategoryListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/infrastructure/ProductCategoryListRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/product/application/ProductServiceImpl.java
  src/main/java/com/jokim/sivillage/api/product/dto/out/ProductListResponseDto.java
  src/main/java/com/jokim/sivillage/api/product/infrastructure/ProductRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/product/infrastructure/ProductRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/product/presentation/ProductController.java
  src/main/java/com/jokim/sivillage/api/product/vo/out/ProductListResponseVo.java
Labels: 🐛 bug

#64 Release-Hotfix: 상품 조회 및 기본 배송지 설정 관련 에러 해결
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/application/ProductCategoryListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/infrastructure/ProductCategoryListRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/customer/application/CustomerServiceImpl.java
  src/main/java/com/jokim/sivillage/api/product/application/ProductServiceImpl.java
  src/main/java/com/jokim/sivillage/api/product/dto/out/ProductListResponseDto.java
  src/main/java/com/jokim/sivillage/api/product/infrastructure/ProductRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/product/infrastructure/ProductRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/product/presentation/ProductController.java
  src/main/java/com/jokim/sivillage/api/product/vo/out/ProductListResponseVo.java
Labels: 🚀 release, 🚑️ hotfix

#66 Release-Hotfix: 카테고리별 상품 조회 API, 위시리스트 전체 조회 API 비즈니스 로직 수정
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/application/ProductCategoryListService.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/application/ProductCategoryListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/infrastructure/ProductCategoryListRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/infrastructure/ProductCategoryListRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/presentation/ProductCategoryListController.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/application/EventWishlistService.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/application/EventWishlistServiceImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/infrastructure/EventWishlistRepository.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/infrastructure/EventWishlistRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/infrastructure/EventWishlistRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/presentation/EventWishlistController.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/application/ProductWishlistService.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/application/ProductWishlistServiceImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/infrastructure/ProductWishlistRepository.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/infrastructure/ProductWishlistRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/infrastructure/ProductWishlistRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/presentation/ProductWishlistController.java
Labels: ✨ enhancement, 🚀 release, 🚑️ hotfix

#67 Hotfix: 카테고리별 상품 조회 API, 위시리스트 전체 조회 API 비즈니스 로직 수정
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/application/ProductCategoryListService.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/application/ProductCategoryListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/infrastructure/ProductCategoryListRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/infrastructure/ProductCategoryListRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/presentation/ProductCategoryListController.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/application/EventWishlistService.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/application/EventWishlistServiceImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/infrastructure/EventWishlistRepository.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/infrastructure/EventWishlistRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/infrastructure/EventWishlistRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/presentation/EventWishlistController.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/application/ProductWishlistService.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/application/ProductWishlistServiceImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/infrastructure/ProductWishlistRepository.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/infrastructure/ProductWishlistRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/infrastructure/ProductWishlistRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/presentation/ProductWishlistController.java
Labels: ✨ enhancement, 🚑️ hotfix

#57 Feature/review
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/infrastructure/ReviewMediaListRepository.java
  src/main/java/com/jokim/sivillage/api/media/infrastructure/MediaRepository.java
  src/main/java/com/jokim/sivillage/api/review/application/ReviewService.java
  src/main/java/com/jokim/sivillage/api/review/application/ReviewServiceImpl.java
  src/main/java/com/jokim/sivillage/api/review/domain/EvaluationItemName.java
  src/main/java/com/jokim/sivillage/api/review/domain/EvaluationItemValue.java
  src/main/java/com/jokim/sivillage/api/review/domain/ProductEvaluationManage.java
  src/main/java/com/jokim/sivillage/api/review/domain/ProductStarAverage.java
  src/main/java/com/jokim/sivillage/api/review/domain/ProductStatistic.java
  src/main/java/com/jokim/sivillage/api/review/domain/Report.java
  src/main/java/com/jokim/sivillage/api/review/domain/Review.java
  src/main/java/com/jokim/sivillage/api/review/domain/ReviewType.java
  src/main/java/com/jokim/sivillage/api/review/dto/in/ReviewRequestDto.java
  src/main/java/com/jokim/sivillage/api/review/dto/out/ReviewResponseDto.java
  src/main/java/com/jokim/sivillage/api/review/dto/out/ReviewSummaryResponseDto.java
  src/main/java/com/jokim/sivillage/api/review/infrastructure/EvaluationItemNameRepository.java
  src/main/java/com/jokim/sivillage/api/review/infrastructure/EvaluationItemValueRepository.java
  src/main/java/com/jokim/sivillage/api/review/infrastructure/ProductEvaluationManageRepository.java
  src/main/java/com/jokim/sivillage/api/review/infrastructure/ProductStarAverageRepository.java
  src/main/java/com/jokim/sivillage/api/review/infrastructure/ProductStatisticRepository.java
  src/main/java/com/jokim/sivillage/api/review/infrastructure/ReportRepository.java
  src/main/java/com/jokim/sivillage/api/review/infrastructure/ReviewRepository.java
  src/main/java/com/jokim/sivillage/api/review/presentation/ReviewController.java
  src/main/java/com/jokim/sivillage/api/review/vo/in/ReviewRequestVo.java
  src/main/java/com/jokim/sivillage/api/review/vo/out/ReviewResponseVo.java
  src/main/java/com/jokim/sivillage/api/review/vo/out/ReviewSummaryResponseVo.java
  src/main/java/com/jokim/sivillage/common/entity/BaseResponseStatus.java
Labels: ✨ enhancement, ♻️ refactor

#72 병합 과정에서 생긴 Compile Error, Media-List 썸네일 조회 API 에러 해결 및 장바구니 API 구현
  src/main/java/com/jokim/sivillage/api/basket/application/BasketService.java
  src/main/java/com/jokim/sivillage/api/basket/application/BasketServiceImpl.java
  src/main/java/com/jokim/sivillage/api/basket/domain/Basket.java
  src/main/java/com/jokim/sivillage/api/basket/domain/BasketState.java
  src/main/java/com/jokim/sivillage/api/basket/dto/in/BasketRequestDto.java
  src/main/java/com/jokim/sivillage/api/basket/dto/out/AllBasketItemsResponseDto.java
  src/main/java/com/jokim/sivillage/api/basket/dto/out/BasketItemCountResponseDto.java
  src/main/java/com/jokim/sivillage/api/basket/dto/out/ExistsInBasketResponseDto.java
  src/main/java/com/jokim/sivillage/api/basket/infrastructure/BasketRepository.java
  src/main/java/com/jokim/sivillage/api/basket/presentation/BasketController.java
  src/main/java/com/jokim/sivillage/api/basket/vo/in/AddToBasketRequestVo.java
  src/main/java/com/jokim/sivillage/api/basket/vo/out/GetAllBasketItemsResponseVo.java
  src/main/java/com/jokim/sivillage/api/basket/vo/out/GetBasketItemCountResponseVo.java
  src/main/java/com/jokim/sivillage/api/basket/vo/out/GetExistsInBasketResponseVo.java
  src/main/java/com/jokim/sivillage/api/brand/dto/out/BrandSummaryResponseDto.java
  src/main/java/com/jokim/sivillage/api/brand/vo/out/GetBrandSummaryResponseVo.java
  src/main/java/com/jokim/sivillage/api/bridge/eventmedialist/application/EventMediaListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/eventmedialist/dto/out/ThumbnailEventMediaListResponseDto.java
  src/main/java/com/jokim/sivillage/api/bridge/eventmedialist/infrastructure/EventMediaListRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/bridge/eventmedialist/infrastructure/EventMediaListRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/productcategorylist/infrastructure/ProductCategoryListRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/application/ProductMediaListService.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/application/ProductMediaListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/dto/out/ThumbnailProductMediaListResponseDto.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/infrastructure/ProductMediaListRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/infrastructure/ProductMediaListRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/productmedialist/presentation/ProductMediaListController.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/infrastructure/ReviewMediaListRepository.java
  src/main/java/com/jokim/sivillage/api/category/vo/in/CreateCategoryRequestVo.java
  src/main/java/com/jokim/sivillage/api/media/domain/MediaType.java
  src/main/java/com/jokim/sivillage/api/product/infrastructure/ProductRepository.java
  src/main/java/com/jokim/sivillage/api/wishlist/brandwishlist/application/BrandWishlistServiceImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/brandwishlist/infrastructure/BrandWishlistRepository.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/application/EventWishlistServiceImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/infrastructure/EventWishlistRepository.java
  src/main/java/com/jokim/sivillage/api/wishlist/eventwishlist/infrastructure/EventWishlistRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/application/ProductWishlistServiceImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/infrastructure/ProductWishlistRepository.java
  src/main/java/com/jokim/sivillage/api/wishlist/productwishlist/infrastructure/ProductWishlistRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/reviewlike/application/ReviewLikeListService.java
  src/main/java/com/jokim/sivillage/api/wishlist/reviewlike/application/ReviewLikeListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/wishlist/reviewlike/domain/ReviewLikeList.java
  src/main/java/com/jokim/sivillage/api/wishlist/reviewlike/dto/ReviewLikeListRequestDto.java
  src/main/java/com/jokim/sivillage/api/wishlist/reviewlike/dto/ReviewLikeListResponseDto.java
  src/main/java/com/jokim/sivillage/api/wishlist/reviewlike/infrastructure/ReviewLikeListRepository.java
  src/main/java/com/jokim/sivillage/api/wishlist/reviewlike/presentation/ReviewLikeListController.java
  src/main/java/com/jokim/sivillage/api/wishlist/reviewlike/vo/AddReviewLikeListRequestVo.java
  src/main/java/com/jokim/sivillage/api/wishlist/reviewlike/vo/GetReviewLikeListResponseVo.java
  src/main/java/com/jokim/sivillage/common/entity/BaseResponseStatus.java
Labels: 🐛 bug, ✨ enhancement, ✅ test, ♻️ refactor

#76 상품 옵션 리스트 반환
  src/main/java/com/jokim/sivillage/api/product/application/ProductService.java
  src/main/java/com/jokim/sivillage/api/product/application/ProductServiceImpl.java
  src/main/java/com/jokim/sivillage/api/product/domain/Product.java
  src/main/java/com/jokim/sivillage/api/product/dto/out/option/ProductOptionResponseDto.java
  src/main/java/com/jokim/sivillage/api/product/infrastructure/ProductRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/product/infrastructure/ProductRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/product/presentation/ProductController.java
  src/main/java/com/jokim/sivillage/api/product/vo/out/ProductOptionResponseVo.java
Labels: ✨ enhancement, ⚡️ improve

#80 ALB health-check Controller 구현 및 예외 처리 수정
  src/main/java/com/jokim/sivillage/api/brand/application/BrandServiceImpl.java
  src/main/java/com/jokim/sivillage/api/brand/infrastructure/BrandRepository.java
  src/main/java/com/jokim/sivillage/api/media/application/MeidaServiceImpl.java
  src/main/java/com/jokim/sivillage/common/aws/StatusCheckController.java
  src/main/java/com/jokim/sivillage/common/config/SecurityConfig.java
Labels: 🐛 bug, ✨ enhancement, ✅ test, 👷 chore

#81 Release: API 구현 (상품 옵션, Best 상품) 구현 및 에러 해결
  src/main/java/com/jokim/sivillage/api/best/product/application/BestProductServiceImpl.java
  src/main/java/com/jokim/sivillage/api/best/product/dto/BestProductResponseDto.java
  src/main/java/com/jokim/sivillage/api/best/product/presentation/BestProductController.java
  src/main/java/com/jokim/sivillage/api/best/product/vo/BestProductResponseVo.java
  src/main/java/com/jokim/sivillage/api/brand/application/BrandServiceImpl.java
  src/main/java/com/jokim/sivillage/api/brand/infrastructure/BrandRepository.java
  src/main/java/com/jokim/sivillage/api/media/application/MeidaServiceImpl.java
  src/main/java/com/jokim/sivillage/api/product/application/ProductService.java
  src/main/java/com/jokim/sivillage/api/product/application/ProductServiceImpl.java
  src/main/java/com/jokim/sivillage/api/product/domain/Product.java
  src/main/java/com/jokim/sivillage/api/product/dto/out/option/ProductOptionResponseDto.java
  src/main/java/com/jokim/sivillage/api/product/infrastructure/ProductRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/product/infrastructure/ProductRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/product/presentation/ProductController.java
  src/main/java/com/jokim/sivillage/api/product/vo/out/ProductOptionResponseVo.java
  src/main/java/com/jokim/sivillage/common/aws/StatusCheckController.java
  src/main/java/com/jokim/sivillage/common/config/SecurityConfig.java
Labels: 🚀 release

#83 Release-Hotfix: 상품에 대한 전체 리뷰 이미지 조회 API, 장바구니 API 구현
  src/main/java/com/jokim/sivillage/api/basket/application/BasketService.java
  src/main/java/com/jokim/sivillage/api/basket/application/BasketServiceImpl.java
  src/main/java/com/jokim/sivillage/api/basket/dto/in/AddBasketRequestDto.java
  src/main/java/com/jokim/sivillage/api/basket/dto/in/DeleteBasketItemRequestDto.java
  src/main/java/com/jokim/sivillage/api/basket/dto/in/UpdateBasketRequestDto.java
  src/main/java/com/jokim/sivillage/api/basket/infrastructure/BasketRepository.java
  src/main/java/com/jokim/sivillage/api/basket/presentation/BasketController.java
  src/main/java/com/jokim/sivillage/api/basket/vo/in/DeleteBasketItemsRequestVo.java
  src/main/java/com/jokim/sivillage/api/basket/vo/in/UpdateBasketItemCheckRequestVo.java
  src/main/java/com/jokim/sivillage/api/basket/vo/in/UpdateBasketItemCountRequestVo.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/application/ReviewMediaListService.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/application/ReviewMediaListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/infrastructure/ReviewMediaListRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/infrastructure/ReviewMediaListRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/presentation/ReviewMediaListController.java
  src/main/java/com/jokim/sivillage/common/entity/BaseResponseStatus.java
Labels: 🚀 release, 🚑️ hotfix

#84 상품에 대한 전체 리뷰 이미지 조회 API, 장바구니 API 구현
  src/main/java/com/jokim/sivillage/api/basket/application/BasketService.java
  src/main/java/com/jokim/sivillage/api/basket/application/BasketServiceImpl.java
  src/main/java/com/jokim/sivillage/api/basket/dto/in/AddBasketRequestDto.java
  src/main/java/com/jokim/sivillage/api/basket/dto/in/DeleteBasketItemRequestDto.java
  src/main/java/com/jokim/sivillage/api/basket/dto/in/UpdateBasketRequestDto.java
  src/main/java/com/jokim/sivillage/api/basket/dto/out/ProductOptionInfoResponseDto.java
  src/main/java/com/jokim/sivillage/api/basket/infrastructure/BasketRepository.java
  src/main/java/com/jokim/sivillage/api/basket/infrastructure/BasketRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/basket/infrastructure/BasketRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/basket/presentation/BasketController.java
  src/main/java/com/jokim/sivillage/api/basket/vo/in/DeleteBasketItemsRequestVo.java
  src/main/java/com/jokim/sivillage/api/basket/vo/in/UpdateBasketItemCheckRequestVo.java
  src/main/java/com/jokim/sivillage/api/basket/vo/in/UpdateBasketItemQuantityRequestVo.java
  src/main/java/com/jokim/sivillage/api/basket/vo/out/GetProductOptionInfoResponseVo.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/application/ReviewMediaListService.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/application/ReviewMediaListServiceImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/infrastructure/ReviewMediaListRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/infrastructure/ReviewMediaListRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/bridge/reviewmedialist/presentation/ReviewMediaListController.java
  src/main/java/com/jokim/sivillage/api/product/domain/ProductOption.java
  src/main/java/com/jokim/sivillage/api/product/infrastructure/ProductOptionRepository.java
  src/main/java/com/jokim/sivillage/common/entity/BaseResponseStatus.java
Labels: ✨ enhancement, ✅ test, 🚑️ hotfix

#86 Release-Hotfix: 장바구니 페이지에서의 상품 옵션 Info 조회 API 구현
  src/main/java/com/jokim/sivillage/api/basket/application/BasketService.java
  src/main/java/com/jokim/sivillage/api/basket/application/BasketServiceImpl.java
  src/main/java/com/jokim/sivillage/api/basket/dto/in/UpdateBasketRequestDto.java
  src/main/java/com/jokim/sivillage/api/basket/dto/out/ProductOptionInfoResponseDto.java
  src/main/java/com/jokim/sivillage/api/basket/infrastructure/BasketRepositoryCustom.java
  src/main/java/com/jokim/sivillage/api/basket/infrastructure/BasketRepositoryImpl.java
  src/main/java/com/jokim/sivillage/api/basket/presentation/BasketController.java
  src/main/java/com/jokim/sivillage/api/basket/vo/in/UpdateBasketItemQuantityRequestVo.java
  src/main/java/com/jokim/sivillage/api/basket/vo/out/GetProductOptionInfoResponseVo.java
  src/main/java/com/jokim/sivillage/api/product/domain/ProductOption.java
  src/main/java/com/jokim/sivillage/api/product/infrastructure/ProductOptionRepository.java
  src/main/java/com/jokim/sivillage/common/entity/BaseResponseStatus.java
Labels: 🚀 release, 🚑️ hotfix
